version: '3'
services:
  app:
    build: .
    command: npm start
    depends_on:
      - mongo
    environment:
      DB_NAME: my_db
      DB_URL: mongodb://root:root@mongo:27017/
      NODE_ENV: development
      WEB_PORT: 9000
    image: memignone/basic-node-app:latest
    ports:
      - "9000:9000"
    volumes:
      - .:/app
  mongo:
    environment:
      MONGO_INITDB_DATABASE: my_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    image: mongo:3.6
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - db_data:/data/db
volumes:
    db_data: