version: '3'

services:
  app:
    build: .
    command: npm start
    depends_on:
      - db
    environment:
      NODE_ENV: development
    ports:
      - "9000:9000"
    volumes:
      - .:/app
  db:
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    image: mongo:3.6
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - db_data:/data/db

volumes:
    db_data: