apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    name: app
  name: app-controller
spec:
  replicas: 1
  selector:
    name: app
  template:
    creationTimestamp: null
    metadata:
      labels:
        name: app
    spec:
      containers:
      - command: ['npm', 'start']
        env:
        - name: DB_NAME
          value: my_db
        - name: DB_URL
          value: mongodb://root:root@mongo:27017/
        - name: NODE_ENV
          value: production
        - name: WEB_PORT
          value: "9000"
        image: memignone/basic-node-app:latest
        name: app
        ports:
        - containerPort: 9000
          name: http-server
      restartPolicy: Always