apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: app
  name: app
spec:
  ports:
    - name: "9000"
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    name: app
  type: LoadBalancer
status: {}