apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    name: mongo
status: {}