apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: my_db
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: mongo:3.6
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: db-data
      restartPolicy: Always
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data